### ISSUE TITLE
Erro avoidz.rb

### ISSUE THREAD

**Issue by d0ubl3puls4r** [M4sc3r4n0/avoidz#3]
When you run the Avoid.rb file, the error message appears:

/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- colorize (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./avoidz.rb:15:in `<main>'

How to solve this problem? I already executed setup.sh, and was downloading the dependencies, but when executing avoidz.sh this error appears above.

**Comment by MeanMachine123** [comment]
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- artii (LoadError)
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./avoidz.rb:16:in `<main>'

Kindly resolve the issue..............

**Comment by mIcHyAmRaNe** [comment]
@d0ubl3puls4r do you have colorize gem installed? 
 `sudo gem install colorize` 

@MeanMachine123 check it you too 
`sudo gem install artii` 

<a href="https://asciinema.org/a/140066"><img src="https://asciinema.org/a/140066.png" width="800"/></a>
